---
title: "Título"
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Introdução à Mecânica Analítica"
#booksubtitle: "Subtítulo do Livro"
bookauthors: "Maia, N. M. M"
bookaddres: "Lisboa"
bookpublisher: "IST Press"
bookyear: "2000"
chaptertitle: "Conceitos Fundamentais"
chapternumber: "2"
maincolor: "e96c34"

output: 
  bookdown::pdf_document2:
    template: template.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\setcounter{section}{7}
\section{PROBLEMAS}

\begin{enumerate}
  \item Verifique se as seguintes expressões são ou não diferenciais exactas:
  \begin{enumerate}[label=\alph*)]
    \item $dU = x^2y dx + y^2x dy$\\
    \iniSol
      Sejam $A_x = x^2 y$ e $S_y = y^2 x$. Temos que $dU$ será uma diferencial exata se, e somente se, $$\dfrac{\partial A_x}{\partial y} = \dfrac{\partial A_y}{\partial x}.$$ Façamos:
      \begin{align*}
        \begin{cases}
          \dfrac{\partial A_x}{\partial y} = x^2\\
          \dfrac{\partial A_y}{\partial y} = y^2
        \end{cases}
        \Rightarrow \dfrac{\partial A_x}{\partial y} \neq \dfrac{\partial A_y}{\partial x}
      \end{align*}
      Portanto, $dU = x^2y dx + y^2x dy$ não é uma diferencial exata.
    \fimSol
    %%
    \item $dU = xy^2 dx + x^2 y dy$\\
    \iniSol
      Sejam $A_x = xy^2$ e $A_y = x^2 y$. Façamos:
      \begin{align*}
        \begin{cases}
          \dfrac{\partial A_x}{\partial y} = xy\\
          \dfrac{\partial A_y}{\partial x} = xy
        \end{cases}
        \Rightarrow \dfrac{\partial A_x}{\partial y} = \dfrac{\partial A_y}{\partial x}
      \end{align*}
      Portanto, $dU = xy^2 dx + x^2 y dy$ é uma diferencial exata, ou seja, $$dU = \dfrac{\partial U}{\partial x} dx + \dfrac{\partial U}{\partial y} dy,$$
      em que $\dfrac{\partial U}{\partial x} = A_x = x y^2$ e $\dfrac{\partial U}{\partial y} = A_y = x^2 y$. A fim de determinar $U = U(x, y)$, façamos:
      \begin{align}
        \dfrac{\partial U}{\partial x} = xy^2 &\Rightarrow U(x, y) = \int xy^2 dx = \dfrac{x^2 y ^2}{2} \nonumber\\
        &\Rightarrow U(x, y) = \dfrac{x^2 y^2}{2} + f(y) \label{eq:U-fy}\\
        \dfrac{\partial U}{\partial y} = x^2 y & \Rightarrow U(x, y) = \int x^2 y dy \nonumber\\
        &\Rightarrow U(x, y) = \dfrac{x^2 y^2}{2} + g(x) \label{eq:U-gx}
      \end{align}
      Comparando os resultados em (\ref{eq:U-fy}) e (\ref{eq:U-gx}), devemos ter:
      $$
      f(y) \equiv g(x) \Rightarrow f(y) = g(x) = \text{cte.}
      $$
      Finalmente, $$U(x, y) = \dfrac{x^2 y^2}{2} + \text{cte.}$$
  
    \fimSol
  \end{enumerate}
  %%
  \item Mostre que as seguintes forças são conservativas:
    \begin{enumerate}[label=\alph*)]
      \item $\vet{F} = \dfrac{3}{5}x^2 y^5 \ux + x^3y^4 \uy$\\
      \iniSol
        Uma força $\vet{F}$ é conservativa quando seu rotacional for identicamente nulo, ou seja, $\text{rot} \vet{F} = \vet{0}$. Assim, 
        \begin{align*}
          \text{rot}\;\vet{F} &= 
          \begin{vmatrix}
            \ux & \uy & \uz\\
            \frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z}\\
            \frac{3}{5}x^2y^5 & x^3y^4 & 0
          \end{vmatrix}\\
          &= \ux \left[\frac{\partial}{\partial y} (0) - \frac{\partial}{\partial z} (x^3y^4)\right] - \uy \left[\dfrac{\partial}{\partial x} (0) - \frac{\partial}{\partial z} \left(\frac{3}{5}x^2y^5\right)\right] + \uz \left[\frac{\partial}{\partial x} (x^3y^4) - \frac{\partial}{\partial y} \left(\frac{3}{5} x^2 y^5\right)\right]\\
          &= \ux (0 - 0) - \uy (0 - 0) + \uz (3x^2y^4 - 3x^2 y^4) \\
          &= 0\ux + 0\uy + 0\uz = \vet{0}
        \end{align*}
      \fimSol
      %%
      \item $\vet{F} = xy^3 \ux + \dfrac{3}{2}x^2 y^2 \uy$\\
      \iniSol
        \begin{align*}
          \text{rot}\;\vet{F} &=
          \begin{vmatrix}
            \ux & \uy & \uz\\
            \frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z}\\
            xy^3 & \frac{3}{2}x^2y^2 & 0
          \end{vmatrix}\\
          &= \ux \left[\dfrac{\partial}{\partial y} (0) - \frac{\partial}{\partial z} \left(\frac{3}{2}x^2y^2\right)\right] + \uy \left[\frac{\partial}{\partial z} (xy^3) - \frac{\partial}{\partial x} (0)\right] + \uz \left[\frac{\partial}{\partial x} \left(\frac{3}{2}x^2y^2\right)- \frac{\partial}{\partial y} (xy^3)\right]\\
          &= \ux (0 - 0) + \uy(0 - 0) + \uz(3xy^2 - 3xy^2)\\
          &= \vet{0}
        \end{align*}
      \fimSol
    \end{enumerate}
    %%
    \item Seja uma força $\vet{F} = 3x^2yz \ux + 3xy^2z \uy + 3xyz^2 \uz$. Calcule a expressão do trabalho elementar efectuado por esta força. Vefifique se esta força é conservativa.\\
    \iniSol
      Seja $\vet{r} = z \ux + y \uy + z \uz \Rightarrow d\vet{r} = dx \ux + dy \uy + dz \uz$. Assim, o trabalho elementar da força dada será:
      \begin{align*}
        \overline{dW} &= \vet{F} \cdot d\vet{r} \\
        &= \left(3x^2yz \ux + 3xy^2z \uy + 3xyz^2 \uz\right) \cdot (dx \ux + dy \uy + dz \uz)\\
        &= 3x^2yz dx + 3xy^2z dy + 3xyz^2 dz
      \end{align*}
      %%
      Para verificar se a força $\vet{F}$ é conservativa, calculemos o seu rotacional:
      \begin{align*}
        \text{rot}\;\vet{F} = 
        \begin{vmatrix}
          \ux & \uy & \uz\\
          \frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z}\\
          F_x & F_y & F_z
        \end{vmatrix}
        &= \ux \left(\frac{\partial F_z}{\partial y} - \frac{\partial F_y}{\partial z}\right) + \uy \left(\dfrac{\partial F_x}{\partial z} - \dfrac{\partial Fz }{\partial x}\right) + \uz \left(\frac{\partial F_y}{\partial x} - \frac{\partial F_x}{\partial y}\right)\\
        &= \ux (3xz^2 - 3xy^2) + \uy (3x^2y - 3yz^2) + \uz (3y^2 z - 3x^2 z)\\
        &= -3x(y^2 - z^2)\ux - 3y(z^2 - x^2) -3z(x^2 - y^2)
      \end{align*}
      %%
      Como $\text{rot}\;\vet{F} \neq \vet{0}$, a força $\vet{F}$ não é conservativa.
    \fimSol
    %%
    \item Mostre que:
    \begin{enumerate}[label=\alph*)]
      \item $\ddot{x}dx = d\left(\frac{1}{2}\dot{x}^2\right)$\\
      \iniSol
        Sejam $x = x(t)$ e $du = \ddot{x}dx$. Então,
        \begin{align*}
          du = \ddot{x}dx &\Rightarrow \dfrac{du}{dt} = \ddot{x}\dfrac{dx}{dt} \Rightarrow \dfrac{du}{dt} = \ddot{x}\dot{x} \Rightarrow \dfrac{du}{dt} = \dfrac{d (\dot{x})}{dt} \dot{x}\\
          &\Rightarrow \dfrac{du}{dt} = \dfrac{1}{2}\dfrac{d (\dot{x})}{dt} \dot{x} + \dfrac{1}{2}\dfrac{d (\dot{x})}{dt} \dot{x}\\
          &\Rightarrow \dfrac{du}{dt} = \dfrac{1}{2}\dfrac{d (\dot{x})}{dt} \dot{x} + \dfrac{1}{2} \dot{x} \dfrac{d (\dot{x})}{dt} \\
          &\Rightarrow \dfrac{du}{dt} = \dfrac{1}{2} \dfrac{d}{dt} \left(\dot{x} \dot{x}\right) = \dfrac{d}{dt}\left(\dfrac{1}{2}\dot{x}^2\right)\\
          &\Rightarrow du = d \left(\dfrac{1}{2}\dot{x}^2\right)\\
          &\Rightarrow \ddot{x}dx = d \left(\dfrac{1}{2}\dot{x}^2\right)
        \end{align*}
      \fimSol
      %%
      \item $d\left(\dot{x}^2\right) = 2\dot{x}\ddot{x}dt$\\
      \iniSol
        \begin{align*}
          \dfrac{d}{dt}\left(\dot{x}^2\right) = 2 \dot{x} \dfrac{d}{dt}(\dot{x}) = 2 \dot{x} \ddot{x} \Rightarrow d\left(\dot{x}^2\right) = 2 \dot{x} \ddot{x} dt
        \end{align*}
      \fimSol
    \end{enumerate}
    %%
    \item Num pêndulo simples (Figura 2.14) mostre que a energia potencial pode ser dada quer por $V = -mgl \cos{\theta}$, quer por $V = mgl (1 - \cos{\theta})$. Justifique.
    %%
    \begin{figure}[H]
      \centering
      \begin{tikzpicture}
        \fill [pattern = north east lines] (-1.5,0) rectangle ++(3,.3);
        \draw[thick] (-1.5,0) -- ++(3,0);
        \draw[thick] (0, 0) -- (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`) node[midway, above, xshift=2pt] {$l$};
        \filldraw[thick, black] (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`) circle (`r 0.15`) node[right, xshift=5pt] {$m$};
        \draw[thick, -latex] (0, -2) arc (270:`r 270+40`:2) node[midway, below] {$\theta$};
        \draw[thick] (0, 0) -- (0, -3);
        \node at (0, 0.8) {Figura 2.14};
      \end{tikzpicture}
    \end{figure}
    %%
    \iniSol
      \textbf{Caso I}: Consideremos inicialmente um referencial cuja origem está situada no ponto de suspensão do pêndulo, conforme mostrado abaixo. Esse ponto coresponderá à origem da energia potencial gravitacional, 
    \begin{figure}[H]
      \centering
      \begin{tikzpicture}
        \fill [pattern = north east lines] (-1.5,0) rectangle ++(3,.3);
        \draw[thick] (-1.5,0) -- ++(3,0);
        \draw[thick] (0, 0) -- (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`);
        \filldraw[thick, black] (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`) circle (`r 0.15`) node[mainColor, right, xshift=5pt] {$A$};
        \draw[thick, -latex] (0, -1.5) arc (270:`r 270+40`:1.5) node[midway, below] {$\theta$};
        \draw[thick] (0, 0) -- (0, -3);
        \node at (0, 0.8) {Caso I};
        %%%
        \draw[mainColor, ultra thick, -latex] (2, -.5) -- (2, -1.5) node[midway, right] {$\vet{g}$};
        \draw[mainColor, thick, latex-latex] (-1.0, -1.5) node[below] {$x$} -- (-2.0,-1.5) -- (-2, -0.5) node[left] {$y$};
        \node[mainColor, below, xshift=-6pt] at (0, 0) {$O$};
        \draw[dashed, mainColor, thick] (0, `r -3*cos(40*pi/180)`) -- (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`);
        \draw [mainColor] (0, `r -3*cos(40*pi/180)`) rectangle ++(0.15, 0.15);
        \draw[latex-latex, mainColor, thick] (-0.5, `r -3*cos(40*pi/180)`) -- (-0.5, 0) node[midway, left] {$l\cos{\theta}$};
        \draw[thick, mainColor] (0, `r -3*cos(40*pi/180)`) -- (-0.6, `r -3*cos(40*pi/180)`);
      \end{tikzpicture}
    \end{figure}
    %%
    A energia potencial no ponto $A$ é dada por:
    $$
    V = -\int_{O}^{A} dW = -\int_{O}^{A} (F_x dx + F_y dy + F_z dz) 
    $$
    em que $F_x = 0$, $F_y = -mg$ e $F_z = 0$. Portanto,
    \begin{align*}
      V &= -\int_{O}^{A} (-mg)\; dy = mg \int_{0}^{-l\cos{\theta}} dy\\
      V &= -mgl\cos{\theta}
    \end{align*}
    %%
    \textbf{Caso II}: Como segunda opção, podemos fixar os eixos coordenados no ponto de equilíbio do pêndulo, conforme mostrado abaixo. Esse ponto corresponderá ao valor nulo da energia potencial.
    \begin{figure}[H]
      \centering
      \begin{tikzpicture}
        \fill [pattern = north east lines] (-1.5,0) rectangle ++(3,.3);
        \draw[thick] (-1.5,0) -- ++(3,0);
        \draw[thick] (0, 0) -- (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`);
        \filldraw[thick, black] (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`) circle (`r 0.15`) node[mainColor, right, xshift=5pt] {$A$};
        \draw[thick, -latex] (0, -1.5) arc (270:`r 270+40`:1.5) node[midway, below] {$\theta$};
        \draw[dashed, thick] (0, 0) -- (0, -3) circle (`r 0.15`);
        \node at (0, 0.8) {Caso II};
        %%%
        \draw[mainColor, ultra thick, -latex] (2, -.5) -- (2, -1.5) node[midway, right] {$\vet{g}$};
        \draw[mainColor, thick, latex-latex] (-1.0, -1.5) node[below] {$x$} -- (-2.0,-1.5) -- (-2, -0.5) node[left] {$y$};
        \node[mainColor, below, xshift=-8pt] at (0, -3) {$O$};
        \draw[dashed, mainColor, thick] (0, `r -3*cos(40*pi/180)`) -- (`r 3*sin(40*pi/180)`, `r -3*cos(40*pi/180)`) -- (0, -3) -- cycle;
        \draw [mainColor] (0, `r -3*cos(40*pi/180)`) rectangle ++(0.15, 0.15);
        \draw[latex-latex, mainColor, thick] (-0.5, `r -3*cos(40*pi/180)`) -- (-0.5, -3) node[midway, left] {$l(1 - \cos{\theta})$};
        \draw[thick, mainColor] (0, -3) -- (-0.6, -3);
        \draw[thick, mainColor] (0, `r -3*cos(40*pi/180)`) -- (-0.6, `r -3*cos(40*pi/180)`);
      \end{tikzpicture}
    \end{figure}
    A energia potencial no ponto $A$ será:
    \begin{align*}
      V &= -\int_{O}^{A} dW = - \int_{0}^{l(1-\cos{\theta})} (-mg)\; dy = mg\left[l(1-cos{\theta}) - 0\right]\\
      V &= mgl (1 - \cos{\theta})
    \end{align*}
    \fimSol
    %%
    \item Supondo que $dV = kxdx$, determine:
    \begin{enumerate}[label=\alph*)]
      \item a derivada de $V$ em ordem a $x$;\\
      \iniSol
      %%
      $$
      \dfrac{dV}{dx} = kx \dfrac{dx}{dx} = kx
      $$
      \fimSol
      %%
      \item a derivada de $V$ em ordem ao tempo;\\
      \iniSol
      %%
      $$
      \dfrac{dV}{dt} = kx \dfrac{dx}{dt} = kx\dot{x}
      $$
      \fimSol
      %%
      \item o valor de $dV$ no intervalo de tempo $dt$.\\
      \iniSol
      %%
      $$\dfrac{dV}{dt} = kx\dot{x} \Rightarrow dV = kx\dot{x} dt$$
      \fimSol
    \end{enumerate}
\end{enumerate}